In [ ]:
#image after preprocessing by svm_model&ResNet50

In [ ]:
import os
import cv2
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from tensorflow.keras.applications.resnet import ResNet50
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.models import Model
import joblib

dataset_path = "/content/drive/MyDrive/ML_Final_Project_Dataset"

def load_images(path):
    images = []
    labels = []
    classes = os.listdir(path)
    for class_name in classes:
        class_path = os.path.join(path, class_name)
        if os.path.isdir(class_path):
            for image_name in os.listdir(class_path):
                image_path = os.path.join(class_path, image_name)
                image = cv2.imread(image_path)
                image = cv2.resize(image, (224, 224))  
                images.append(image)
                labels.append(class_name)
    return images, labels

images, labels = load_images(dataset_path)

images = np.array(images)
labels = np.array(labels)

label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

n_samples, img_height, img_width, _ = images.shape
images = images.reshape(n_samples, img_height, img_width, 3)

k = 5
skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
accuracies = []
f1_scores = []
confusion_matrices = []

for fold_index, (train_index, test_index) in enumerate(skf.split(images, labels)):
    print("Fold:", fold_index + 1)
    X_train, X_test = images[train_index], images[test_index]
    y_train, y_test = labels[train_index], labels[test_index]

    base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    model = Model(inputs=base_model.input, outputs=x)

    X_train_features = model.predict(X_train)
    X_test_features = model.predict(X_test)

    classifier = SVC(kernel='poly')
    classifier.fit(X_train_features, y_train)

    y_pred = classifier.predict(X_test_features)

    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)
    print("Accuracy:", accuracy)

    f1 = f1_score(y_test, y_pred, average='macro')
    f1_scores.append(f1)
    print("F1 Score:", f1)

    cm = confusion_matrix(y_test, y_pred)
    confusion_matrices.append(cm)
    print("Confusion Matrix:")
    print(cm)

    model_filename = f'/content/drive/MyDrive/gogo/svm_model&ResNet50_fold_{fold_index + 1}.joblib'
    joblib.dump(classifier, model_filename)
    print("Model saved successfully:", model_filename)

mean_accuracy = np.mean(accuracies)
mean_f1 = np.mean(f1_scores)
print("Mean Accuracy:", mean_accuracy)
print("Mean F1 Score:", mean_f1)


Fold: 1
9/9 [==============================] - 1s 84ms/step
Accuracy: 0.9379562043795621
F1 Score: 0.9218897785269466
Confusion Matrix:
[[152   0   4]
 [  2  56   1]
 [  5   5  49]]
Model saved successfully: /content/drive/MyDrive/gogo/svm_model&ResNet50_fold_1.joblib
Fold: 2
9/9 [==============================] - 1s 84ms/step
Accuracy: 0.9306569343065694
F1 Score: 0.9134737814737814
Confusion Matrix:
[[150   1   5]
 [  5  49   5]
 [  1   2  56]]
Model saved successfully: /content/drive/MyDrive/gogo/svm_model&ResNet50_fold_2.joblib
Fold: 3
9/9 [==============================] - 1s 85ms/step
Accuracy: 0.916058394160584
F1 Score: 0.9009394614430447
Confusion Matrix:
[[147   1   8]
 [  1  54   4]
 [  7   2  50]]
Model saved successfully: /content/drive/MyDrive/gogo/svm_model&ResNet50_fold_3.joblib
Fold: 4
9/9 [==============================] - 1s 89ms/step
Accuracy: 0.9416058394160584
F1 Score: 0.9250814226717189
Confusion Matrix:
[[152   0   4]
 [  1  55   3]
 [  4   4  51]]
Model saved 

In [ ]:
#image after preprocessing by Logistic&ResNet50

In [ ]:
import os
import cv2
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.applications.resnet import ResNet50
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.models import Model

dataset_path = "/content/drive/MyDrive/ML_Final_Project_Dataset"

def load_images(path):
    images = []
    labels = []
    classes = os.listdir(path)
    for class_name in classes:
        class_path = os.path.join(path, class_name)
        if os.path.isdir(class_path):
            for image_name in os.listdir(class_path):
                image_path = os.path.join(class_path, image_name)
                image = cv2.imread(image_path)
                image = cv2.resize(image, (224, 224))  
                images.append(image)
                labels.append(class_name)
    return images, labels

images, labels = load_images(dataset_path)

images = np.array(images)
labels = np.array(labels)

label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

n_samples, img_height, img_width, _ = images.shape
images = images.reshape(n_samples, img_height, img_width, 3)

k = 5
skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
accuracies = []
f1_scores = []
confusion_matrices = []

for fold_index, (train_index, test_index) in enumerate(skf.split(images, labels)):
    print("Fold:", fold_index + 1)
    X_train, X_test = images[train_index], images[test_index]
    y_train, y_test = labels[train_index], labels[test_index]

    base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    model = Model(inputs=base_model.input, outputs=x)

    X_train_features = model.predict(X_train)
    X_test_features = model.predict(X_test)

    from sklearn.linear_model import LogisticRegression

    classifier = LogisticRegression(max_iter=1000)
    classifier.fit(X_train_features, y_train)

    y_pred = classifier.predict(X_test_features)

    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)
    print("Accuracy:", accuracy)

    f1 = f1_score(y_test, y_pred, average='macro')
    f1_scores.append(f1)
    print("F1 Score:", f1)

    cm = confusion_matrix(y_test, y_pred)
    confusion_matrices.append(cm)
    print("Confusion Matrix:")
    print(cm)

    model_filename = f'/content/drive/MyDrive/gogo/Logistic&ResNet50_fold_{fold_index + 1}.joblib'
    joblib.dump(classifier, model_filename)
    print("Model saved successfully:", model_filename)

mean_accuracy = np.mean(accuracies)
mean_f1 = np.mean(f1_scores)
print("Mean Accuracy:", mean_accuracy)
print("Mean F1 Score:", mean_f1)


Fold: 1
9/9 [==============================] - 1s 84ms/step
Accuracy: 0.9598540145985401
F1 Score: 0.94677769533075
Confusion Matrix:
[[153   1   2]
 [  1  56   2]
 [  1   4  54]]
Model saved successfully: /content/drive/MyDrive/gogo/Logistic&ResNet50_fold_1.joblib
Fold: 2
9/9 [==============================] - 1s 91ms/step
Accuracy: 0.9452554744525548
F1 Score: 0.9329572686468866
Confusion Matrix:
[[151   1   4]
 [  3  52   4]
 [  2   1  56]]
Model saved successfully: /content/drive/MyDrive/gogo/Logistic&ResNet50_fold_2.joblib
Fold: 3
9/9 [==============================] - 1s 84ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.9306569343065694
F1 Score: 0.913312411322916
Confusion Matrix:
[[149   1   6]
 [  0  54   5]
 [  4   3  52]]
Model saved successfully: /content/drive/MyDrive/gogo/Logistic&ResNet50_fold_3.joblib
Fold: 4
9/9 [==============================] - 1s 92ms/step
Accuracy: 0.9598540145985401
F1 Score: 0.9466075535182356
Confusion Matrix:
[[154   0   2]
 [  1  54   4]
 [  2   2  55]]
Model saved successfully: /content/drive/MyDrive/gogo/Logistic&ResNet50_fold_4.joblib
Fold: 5
9/9 [==============================] - 1s 90ms/step
Accuracy: 0.945054945054945
F1 Score: 0.9314994636903533
Confusion Matrix:
[[152   0   3]
 [  1  56   2]
 [  6   3  50]]
Model saved successfully: /content/drive/MyDrive/gogo/Logistic&ResNet50_fold_5.joblib
Mean Accuracy: 0.9481350766022298
Mean F1 Score: 0.9342308785018283


In [ ]:
# orginal image by svm_model&ResNet50

In [ ]:
import os
import cv2
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from tensorflow.keras.applications.resnet import ResNet50
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.models import Model
import joblib

dataset_path = "/content/drive/MyDrive/archive (4)"

def load_images(path):
    images = []
    labels = []
    classes = os.listdir(path)
    for class_name in classes:
        class_path = os.path.join(path, class_name)
        if os.path.isdir(class_path):
            for image_name in os.listdir(class_path):
                image_path = os.path.join(class_path, image_name)
                image = cv2.imread(image_path)
                image = cv2.resize(image, (224, 224))  
                images.append(image)
                labels.append(class_name)
    return images, labels

images, labels = load_images(dataset_path)

images = np.array(images)
labels = np.array(labels)

label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

n_samples, img_height, img_width, _ = images.shape
images = images.reshape(n_samples, img_height, img_width, 3)

k = 5
skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
accuracies = []
f1_scores = []
confusion_matrices = []

for fold_index, (train_index, test_index) in enumerate(skf.split(images, labels)):
    print("Fold:", fold_index + 1)
    X_train, X_test = images[train_index], images[test_index]
    y_train, y_test = labels[train_index], labels[test_index]

    base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    model = Model(inputs=base_model.input, outputs=x)

    X_train_features = model.predict(X_train)
    X_test_features = model.predict(X_test)

    classifier = SVC(kernel='poly')
    classifier.fit(X_train_features, y_train)

    y_pred = classifier.predict(X_test_features)

    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)
    print("Accuracy:", accuracy)

   
    f1 = f1_score(y_test, y_pred, average='macro')
    f1_scores.append(f1)
    print("F1 Score:", f1)


    cm = confusion_matrix(y_test, y_pred)
    confusion_matrices.append(cm)
    print("Confusion Matrix:")
    print(cm)

    model_filename = f'/content/drive/MyDrive/gogo/orginal_svm_model&ResNet50_fold_{fold_index + 1}.joblib'
    joblib.dump(classifier, model_filename)
    print("Model saved successfully:", model_filename)

mean_accuracy = np.mean(accuracies)
mean_f1 = np.mean(f1_scores)
print("Mean Accuracy:", mean_accuracy)
print("Mean F1 Score:", mean_f1)


Fold: 1
9/9 [==============================] - 1s 84ms/step
Accuracy: 0.9343065693430657
F1 Score: 0.9177547742624217
Confusion Matrix:
[[150   0   6]
 [  0  56   3]
 [  5   4  50]]
Model saved successfully: /content/drive/MyDrive/gogo/orginal_svm_model&ResNet50_fold_1.joblib
Fold: 2
9/9 [==============================] - 1s 93ms/step
Accuracy: 0.9525547445255474
F1 Score: 0.9422583680138777
Confusion Matrix:
[[150   1   5]
 [  0  59   0]
 [  3   4  52]]
Model saved successfully: /content/drive/MyDrive/gogo/orginal_svm_model&ResNet50_fold_2.joblib
Fold: 3
9/9 [==============================] - 1s 91ms/step
Accuracy: 0.9635036496350365
F1 Score: 0.9608942602573176
Confusion Matrix:
[[152   0   4]
 [  1  58   0]
 [  5   0  54]]
Model saved successfully: /content/drive/MyDrive/gogo/orginal_svm_model&ResNet50_fold_3.joblib
Fold: 4
9/9 [==============================] - 1s 91ms/step
Accuracy: 0.9306569343065694
F1 Score: 0.9182920328278804
Confusion Matrix:
[[145   4   7]
 [  0  59   0]
 [ 

In [ ]:
#orginal image preprocessing by Logistic&ResNet50

In [3]:
import os
import cv2
import numpy as np
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score, f1_score, confusion_matrix
from sklearn.preprocessing import LabelEncoder
from tensorflow.keras.applications.resnet import ResNet50
from tensorflow.keras.layers import GlobalAveragePooling2D
from tensorflow.keras.models import Model
import joblib

dataset_path = "/content/drive/MyDrive/archive (4)"

def load_images(path):
    images = []
    labels = []
    classes = os.listdir(path)
    for class_name in classes:
        class_path = os.path.join(path, class_name)
        if os.path.isdir(class_path):
            for image_name in os.listdir(class_path):
                image_path = os.path.join(class_path, image_name)
                image = cv2.imread(image_path)
                image = cv2.resize(image, (224, 224))  
                images.append(image)
                labels.append(class_name)
    return images, labels

images, labels = load_images(dataset_path)

images = np.array(images)
labels = np.array(labels)

label_encoder = LabelEncoder()
labels = label_encoder.fit_transform(labels)

n_samples, img_height, img_width, _ = images.shape
images = images.reshape(n_samples, img_height, img_width, 3)

k = 5
skf = StratifiedKFold(n_splits=k, shuffle=True, random_state=42)
accuracies = []
f1_scores = []
confusion_matrices = []

for fold_index, (train_index, test_index) in enumerate(skf.split(images, labels)):
    print("Fold:", fold_index + 1)
    X_train, X_test = images[train_index], images[test_index]
    y_train, y_test = labels[train_index], labels[test_index]

    base_model = ResNet50(weights='imagenet', include_top=False, input_shape=(224, 224, 3))
    x = base_model.output
    x = GlobalAveragePooling2D()(x)
    model = Model(inputs=base_model.input, outputs=x)

    X_train_features = model.predict(X_train)
    X_test_features = model.predict(X_test)

    from sklearn.linear_model import LogisticRegression

    classifier = LogisticRegression(max_iter=1000)
    classifier.fit(X_train_features, y_train)

    y_pred = classifier.predict(X_test_features)

    accuracy = accuracy_score(y_test, y_pred)
    accuracies.append(accuracy)
    print("Accuracy:", accuracy)

    f1 = f1_score(y_test, y_pred, average='macro')
    f1_scores.append(f1)
    print("F1 Score:", f1)

    cm = confusion_matrix(y_test, y_pred)
    confusion_matrices.append(cm)
    print("Confusion Matrix:")
    print(cm)

    model_filename = f'/content/drive/MyDrive/gogo2/orginalLogistic&ResNet50_fold_{fold_index + 1}.joblib'
    joblib.dump(classifier, model_filename)
    print("Model saved successfully:", model_filename)

mean_accuracy = np.mean(accuracies)
mean_f1 = np.mean(f1_scores)
print("Mean Accuracy:", mean_accuracy)
print("Mean F1 Score:", mean_f1)


Fold: 1
9/9 [==============================] - 1s 89ms/step


/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


Accuracy: 0.9598540145985401
F1 Score: 0.9463634426000326
Confusion Matrix:
[[153   0   3]
 [  0  58   1]
 [  2   5  52]]
Model saved successfully: /content/drive/MyDrive/gogo2/orginalLogistic&ResNet50_fold_1.joblib
Fold: 2
9/9 [==============================] - 1s 86ms/step
Accuracy: 0.9452554744525548
F1 Score: 0.9362326127032009
Confusion Matrix:
[[150   1   5]
 [  3  56   0]
 [  3   3  53]]
Model saved successfully: /content/drive/MyDrive/gogo2/orginalLogistic&ResNet50_fold_2.joblib
Fold: 3
9/9 [==============================] - 1s 85ms/step
Accuracy: 0.9744525547445255
F1 Score: 0.9716873009555936
Confusion Matrix:
[[151   0   5]
 [  0  58   1]
 [  1   0  58]]
Model saved successfully: /content/drive/MyDrive/gogo2/orginalLogistic&ResNet50_fold_3.joblib
Fold: 4
9/9 [==============================] - 1s 85ms/step
Accuracy: 0.9598540145985401
F1 Score: 0.9519049688541213
Confusion Matrix:
[[152   2   2]
 [  1  56   2]
 [  3   1  55]]
Model saved successfully: /content/drive/MyDrive/g